version: "3"
services:
#  consul:
#      image: consul:latest
#      container_name: consul
#      ports:
#        - "8500:8500"    # Consul HTTP API
#        - "8600:8600"    # DNS interface
#      volumes:
#        - consul-data:/consul/data
#      command: "agent -server -dev -ui -client=0.0.0.0"

  app:
    image: monitoring-demo:latest
    container_name: 'monitoring-demo'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
    - ./monitoring/prometheus/:/etc/prometheus/
    ports:
    - '9090:9090'
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:11.2.0
    container_name: 'grafana'
    ports:
    - '3000:3000'
    volumes:
    - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    - ./monitoring/grafana/provisioning/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./monitoring/grafana/dashboards/:/etc/grafana/dashboards/
    env_file:
    - ./monitoring/grafana/config.monitoring
    networks:
      - monitoring
    depends_on:
    - prometheus
  zipkin:
    image: openzipkin/zipkin:2.23.1
    container_name: 'zipkin'
    networks:
      - monitoring
    ports:
      - '9411:9411'
networks:
  monitoring:
    driver: bridge

volumes:
  consul-data:

