global:
  resolve_timeout: 5m

route:
  receiver: 'grafana'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'grafana'
    webhook_configs:
      - url: 'http://host.docker.internal:3000/api/prom/alertmanager'  # Grafana webhook URL
