groups:
  - name: api-gateway-latency-alert
    rules:
      - alert: HighScrapeLatency
        expr: scrape_duration_seconds{job="vericash-core-services-without-consul"} > 0.5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High scrape duration on api-gateway"
  - name: service-scrape-down
    rules:
      - alert: ScrapeJobDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 seconds."