{
 "title": "Production",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Uptime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "The starttime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  { "title": "CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Processor Count",
   "type": "singlestat",
   "description": "The number of processors available to the Java virtual machine",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Average CPU Load",
   "type": "graph",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_load_average_1m" }
   ]
  },
  { "title": "Logback Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Warn Events",
   "type": "singlestat",
   "description": "Number of warn level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logback_events_total{level=\"warn\"}"
    }
   ]
  },
  {
   "title": "Debug Events",
   "type": "singlestat",
   "description": "Number of debug level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logback_events_total{level=\"debug\"}"
    }
   ]
  },
  {
   "title": "Error Events",
   "type": "singlestat",
   "description": "Number of error level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logback_events_total{level=\"error\"}"
    }
   ]
  },
  {
   "title": "Trace Events",
   "type": "singlestat",
   "description": "Number of trace level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logback_events_total{level=\"trace\"}"
    }
   ]
  },
  {
   "title": "Info Events",
   "type": "singlestat",
   "description": "Number of info level events that made it to the logs",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logback_events_total{level=\"info\"}"
    }
   ]
  },
  { "title": "JVM Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "JVM Threads Peak",
   "type": "graph",
   "description": "The peak live thread count since the Java virtual machine started or peak was reset",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_peak_threads" }
   ]
  },
  {
   "title": "Live Daemon Threads",
   "type": "graph",
   "description": "The current number of live daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_daemon_threads" }
   ]
  },
  {
   "title": "Live Total Threads",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  { "title": "JVM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Buffer Count",
   "type": "graph",
   "description": "An estimate of the number of buffers in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Buffer Mem Used",
   "type": "graph",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Buffer Capacity",
   "type": "graph",
   "description": "An estimate of the total capacity of the buffers in this pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "graph",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  { "title": "JVM Garbage Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Max Data Size",
   "type": "graph",
   "description": "Max size of old generation memory pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_gc_max_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "graph",
   "description": "Size of old generation memory pool after a full GC",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Pause Count",
   "type": "graph",
   "description": "Time spent in GC pause",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "jvm_gc_pause_seconds_count" }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "graph",
   "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total"
    }
   ]
  },
  { "title": "HTTP Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "HTTP Requests Count",
   "type": "graph",
   "description": "Count of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Time",
   "type": "graph",
   "description": "Timer of servlet requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  }
 ]
}