global:
  scrape_interval:   15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'bootifull-monitoring'

scrape_configs:
- job_name:       'monitoring-demo'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'

  static_configs:
  - targets: ['host.docker.internal:8080']
    labels:
      application: 'monitoring-demo'

- job_name: 'prometheus'

  scrape_interval: 5s

  static_configs:
  - targets: ['localhost:9090']

- job_name:       'zipkin-service-1'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 2s
  metrics_path: '/actuator/prometheus'

  static_configs:
    - targets: ['host.docker.internal:8081']
      labels:
        application: 'zipkin-service-1'

- job_name:       'zipkin-service-2'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 2s
  metrics_path: '/actuator/prometheus'

  static_configs:
    - targets: ['host.docker.internal:8082']
      labels:
        application: 'zipkin-service-2'

- job_name:       'zipkin-service-3'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 2s
  metrics_path: '/actuator/prometheus'

  static_configs:
    - targets: ['host.docker.internal:8083']
      labels:
        application: 'zipkin-service-3'

- job_name:       'zipkin-service-4'

  # Override the global default and scrape targets from this job every 10 seconds.
  scrape_interval: 2s
  metrics_path: '/actuator/prometheus'

  static_configs:
    - targets: ['host.docker.internal:8084']
      labels:
        application: 'zipkin-service-4'