#apiVersion: 1
#groups:
#  - orgId: 1
#    name: evaluationUp
#    folder: Alerting
#    interval: 1m
#    rules:
#      - uid: ce1ecmevzturke
#        title: Up
#        condition: C
#        data:
#          - refId: A
#            relativeTimeRange:
#              from: 600
#              to: 0
#            datasourceUid: PBFA97CFB590B2093
#            model:
#              disableTextWrap: false
#              editorMode: builder
#              expr: up
#              fullMetaSearch: false
#              includeNullMetadata: true
#              instant: true
#              intervalMs: 1000
#              legendFormat: __auto
#              maxDataPoints: 43200
#              range: false
#              refId: A
#              useBackend: false
#          - refId: C
#            relativeTimeRange:
#              from: 600
#              to: 0
#            datasourceUid: __expr__
#            model:
#              conditions:
#                - evaluator:
#                    params:
#                      - 0
#                    type: gt
#                  operator:
#                    type: and
#                  query:
#                    params:
#                      - C
#                  reducer:
#                    params: []
#                    type: last
#                  type: query
#              datasource:
#                type: __expr__
#                uid: __expr__
#              expression: A
#              intervalMs: 1000
#              maxDataPoints: 43200
#              refId: C
#              type: threshold
#        noDataState: NoData
#        execErrState: Error
#        for: 0s
#        annotations:
#          description: ""
#          runbook_url: ""
#          summary: ""
#        labels:
#          "": ""
#          severity: critical
#        isPaused: false
#        notification_settings:
#          receiver: CIT Email Alerts
#          group_by:
#            - grafana_folder
#            - alertname
#          group_wait: 0s
#          group_interval: 30m
#          repeat_interval: 1h
